apiVersion: v1
kind: Workflow
metadata:
  name: thinknyapp-svc
  labels:
    app: thinknyapp
spec:
  type: NodePort
  selector:
    app: thinknyapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 30007
