apiVersion: v1
kind: service
metadata:
  name: thinknyxapp-svc
  labels:
    app: thinknyxapp
spec:
  type: NodePort
  selector:
    app: thinknyxapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 30007
